version: 0.1

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 421148638783.dkr.ecr.ap-southeast-1.amazonaws.com
  build:
    commands:
      - echo Building Docker image...
      - docker build -t flappybird-ecr .
      - docker tag flappybird-ecr:latest 421148638783.dkr.ecr.ap-southeast-1.amazonaws.com/flappybird-ecr:latest
  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - docker push 421148638783.dkr.ecr.ap-southeast-1.amazonaws.com/flappybird-ecr:latest

artifacts:
  files:
    - "**/*"
  discard-paths: yes
